swagger: '2.0'
info:
  version: '1.0'
  title: "NoName API project"
  description: UNITN - Ingegneria del software 2 project
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: noname-unitn-ingsw2.herokuapp.com
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /login:
    x-summary: Login
    post:
      summary: Send login data
      responses:
        200:
          description: Logged in correctly
        401:
          description: User not logged in correctly

  /users:
    get:
      summary: List users registered with specific filters
      responses:
        200:
          description: Successful Response
        401:
          description: User not logged in
    post:
      summary: Create a new user
      responses:
        201:
          description: Successful creation
  /users/{userId}:
    parameters:
    - name: "userId"
      in: "path"
      description: "id of the user"
      required: true
      type: "integer"
      format: "int64"
    get:
      summary: Get registered user by id
      responses:
        200:
          description: Successful response
        401:
          description: User not logged in
    put:
      summary: Update a user info
      responses:
        200:
          description: Successful response
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action
    delete:
      summary: Delete a user
      responses:
        200:
          description: Successful response
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action
          
  /exams:
    get:
      summary: List all the exams that the user created or is assigned to
      responses:
        200:
          description: Successful Response
        401:
          description: User not logged in
    post:
      summary: Create a new exam
      responses:
        201:
          description: Successful creation
        401:
          description: User not logged in
  /exams/{examId}:
    parameters:
    - name: "examId"
      in: "path"
      description: "id of the exam"
      required: true
      type: "integer"
      format: "int64"
    get:
      summary: Get exam by id
      responses:
        200:
          description: Successful response
        401:
          description: User not logged in
        403:
          description: Not authorized to view this item
    put:
      summary: Update a exam
      responses:
        200:
          description: Successful response
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action
    delete:
      summary: Delete a exam
      responses:
        200:
          description: Successful response
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action
          
  /exams/{examId}/teacherassistants:
    parameters:
    - name: "examId"
      in: "path"
      description: "id of the exam"
      required: true
      type: "integer"
      format: "int64"
    get:
      summary: List all the teacher assistants assigned to the exam
      responses:
        200:
          description: Successful Response
        401:
          description: User not logged in
    post:
      summary: Add a new teacher assistant
      responses:
        201:
          description: Successful add
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action
          
  
  /exams/{examId}/teacherassistants/{taId}:
    parameters:
    - name: "examId"
      in: "path"
      description: "id of the exam"
      required: true
      type: "integer"
      format: "int64"
    - name: "taId"
      in: "path"
      description: "id of the exam"
      required: true
      type: "integer"
      format: "int64"
    delete:
      summary: Delete a teacher assistant
      responses:
        200:
          description: Successful response
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action
          
  /exams/{examId}/tasks:
    parameters:
    - name: "examId"
      in: "path"
      description: "id of the exam"
      required: true
      type: "integer"
      format: "int64"
    get:
      summary: List all the tasks or the tasks assigned to the user based on filters
      responses:
        200:
          description: Successful Response
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action
    post:
      summary: Add a new task
      responses:
        201:
          description: Successful add
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action
          
  /exams/{examId}/tasks/{taskId}:
    parameters:
    - name: "examId"
      in: "path"
      description: "id of the exam"
      required: true
      type: "integer"
      format: "int64"
    - name: "taskId"
      in: "path"
      description: "id of the task"
      required: true
      type: "integer"
      format: "int64"
    get:
      summary: Get task by id in the current exam
      responses:
        200:
          description: Successful response
        401:
          description: User not logged in
        403:
          description: Not authorized to view this item
    put:
      summary: Update a task info
      responses:
        200:
          description: Successful response
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action
    delete:
      summary: Delete a task
      responses:
        200:
          description: Successful response
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action          
          
          
  /exams/{examId}/members:
    parameters:
    - name: "examId"
      in: "path"
      description: "id of the exam"
      required: true
      type: "integer"
      format: "int64"
    get:
      summary: List all the students assigned to the current exam
      responses:
        200:
          description: Successful Response
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action
    post:
      summary: Add a new student
      responses:
        201:
          description: Successful add
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action
          
  /exams/{examId}/members/{userId}:
    parameters:
    - name: "examId"
      in: "path"
      description: "id of the exam"
      required: true
      type: "integer"
      format: "int64"
    - name: "userId"
      in: "path"
      description: "id of the student"
      required: true
      type: "integer"
      format: "int64"
    delete:
      summary: Delete a task
      responses:
        200:
          description: Successful response
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action  
          
          
  /exams/{examId}/tasks/{taskId}/submissions:
    parameters:
    - name: "examId"
      in: "path"
      description: "id of the exam"
      required: true
      type: "integer"
      format: "int64"
    - name: "taskId"
      in: "path"
      description: "id of the task"
      required: true
      type: "integer"
      format: "int64"
    get:
      summary: List all the submissions made by the user on the current task
      responses:
        200:
          description: Successful Response
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action
    post:
      summary: Add a new submission
      responses:
        201:
          description: Successful add
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action, deadline reached or user not assigned to the current exam/task

  /exams/{examId}/tasks/{taskId}/submissions/last:
    parameters:
    - name: "examId"
      in: "path"
      description: "id of the exam"
      required: true
      type: "integer"
      format: "int64"
    - name: "taskId"
      in: "path"
      description: "id of the task"
      required: true
      type: "integer"
      format: "int64"
    get:
      summary: List the last submission made by the user on the current task
      responses:
        200:
          description: Successful Response
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action  
          
  /exams/{examId}/tasks/{taskId}/submissions/{subId}:
    parameters:
    - name: "examId"
      in: "path"
      description: "id of the exam"
      required: true
      type: "integer"
      format: "int64"
    - name: "taskId"
      in: "path"
      description: "id of the task"
      required: true
      type: "integer"
      format: "int64"
    - name: "subId"
      in: "path"
      description: "id of the submission"
      required: true
      type: "integer"
      format: "int64"
    get:
      summary: Get submission by id in the current task
      responses:
        200:
          description: Successful response
        401:
          description: User not logged in
        403:
          description: Not authorized to view this item
          
  /exams/{examId}/tasks/{taskId}/submissions/{subId}/reviewer:
    parameters:
    - name: "examId"
      in: "path"
      description: "id of the exam"
      required: true
      type: "integer"
      format: "int64"
    - name: "taskId"
      in: "path"
      description: "id of the task"
      required: true
      type: "integer"
      format: "int64"
    - name: "subId"
      in: "path"
      description: "id of the submission"
      required: true
      type: "integer"
      format: "int64"
    put:
      summary: Set the student that have to review and comment the submission.
      responses:
        200:
          description: Successful response
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action
          
  /exams/{examId}/tasks/{taskId}/submissions/{subId}/review:
    parameters:
    - name: "examId"
      in: "path"
      description: "id of the exam"
      required: true
      type: "integer"
      format: "int64"
    - name: "taskId"
      in: "path"
      description: "id of the task"
      required: true
      type: "integer"
      format: "int64"
    - name: "subId"
      in: "path"
      description: "id of the submission"
      required: true
      type: "integer"
      format: "int64"
    post:
      summary: Submit a review as a reviewer for the current submission
      responses:
        201:
          description: Successful submit
        401:
          description: User not logged in
        403:
          description: Not authorized to do this action